### ISSUE TITLE
[BUG]:  when clicking on 'use this template', if not selected 'include all branches' git annex is not "forked" into the new repo

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/template_datalad_fMRI#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

**Comment by Remi-Gau** [comment]
Should not be an issue as no "data" actually is supposed to live in this YODA dataset.

But could be an issue if someone wants to actually host data in there.
