### ISSUE TITLE
Update submodule CPP_SPM to bidspm

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/template_datalad_fMRI#26]
Fit is probably smart enough to get it by itself but we prefer consistency.

@Remi-Gau I can take care of this, I would deactivate the submodule and reactivate it with the new URL. Do you confirm this is the rightway?

**Comment by Remi-Gau** [comment]
may even be enough to update these URL, no?

https://github.com/cpp-lln-lab/template_datalad_fMRI/blob/fd92f292138559c924e61cacccfba659a40a610f/.gitmodules#L3

**Comment by marcobarilari** [comment]
Yeah, Ithought about that but it sounded too easy... let me try
